<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <artifactId>web-server</artifactId>
    <build>
        <plugins>
            <plugin>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <layout>WAR</layout>
                    <mainClass>less.lgeo.WebServer</mainClass>
                    <outputTimestamp/>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <groupId>org.springframework.boot</groupId>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <artifactId>spring-boot-starter-web</artifactId>
            <groupId>org.springframework.boot</groupId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-test</artifactId>
            <groupId>org.springframework.boot</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>modeling</artifactId>
            <groupId>less.lgeo</groupId>
            <scope>compile</scope>

        </dependency>
        <dependency>
            <artifactId>modeling</artifactId>
            <groupId>less.lgeo</groupId>
            <type>test-jar</type>
            <scope>test</scope>

        </dependency>
        <dependency>
            <artifactId>messaging</artifactId>
            <groupId>less.lgeo</groupId>
            <scope>compile</scope>

        </dependency>
        <dependency>
            <artifactId>database</artifactId>
            <groupId>less.lgeo</groupId>
            <scope>compile</scope>

        </dependency>
        <dependency>
            <groupId>io.zonky.test</groupId>
            <artifactId>embedded-database-spring-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <parent>
        <artifactId>bom</artifactId>
        <groupId>less.lgeo</groupId>
        <relativePath>../bom/pom.xml</relativePath>
        <version>0.0.2-SNAPSHOT</version>
    </parent>
</project>
