spring:
  application:
    name: LessLGEO
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/color?currentSchema=color
    username: { DATABASE_USER }
    password: { DATABASE_PASSWORD }


rabbit:
  bindings:
    web-to-parser:
      exchange: "web-to-parser-exchange"
      queue: "web-to-parser-queue"
      routingKey: "web.parser.#"
    web-to-color:
    parser-to-reducer:
      exchange: "parser-to-reducer-exchange"
      queue: "parser-to-reducer-queue"
      routingKey: "parser.reducer.#"