services:
  postgres:
    image: postgres:latest
    container_name: LessLGEO-postgres-1
    ports:
      - "5432:5432"  # PostgreSQL port
    environment:
      POSTGRES_DB: mydatabase           # Name of the default database
      POSTGRES_USER: myuser             # Default user to create
      POSTGRES_PASSWORD: mypassword     # Password for the user
      PGDATA: /var/lib/postgresql/data/pgdata
      # Optional: Customize the path PostgreSQL stores data in the container
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.3
    container_name: LessLGEO-pg-admin-1
    ports:
      - "5050:80"  # Maps pgAdmin to http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com   # Login email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: adminpassword     # Login password for pgAdmin
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
      # Persists pgAdmin configuration and server state

volumes:
  postgres_volume:
  # Persistent storage for PostgreSQL data files
  pgadmin_volume:
  # Persistent storage for pgAdmin user settings and servers

