<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>parent</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <groupId>org.springframework.boot</groupId>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>spring-boot-starter-logging</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>3.4.4</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-amqp</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-docker-compose</artifactId>
      <groupId>org.springframework.boot</groupId>
      <optional>true</optional>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-rabbit-test</artifactId>
      <groupId>org.springframework.amqp</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>snakeyaml</artifactId>
      <groupId>org.yaml</groupId>
      <version>2.4</version>
    </dependency>
  </dependencies>
  <description>Minimize legos needed</description>
  <developers>
    <developer>
      <email>ryangross47@gmail.com</email>
      <name>Ryan Gross</name>
    </developer>
  </developers>
  <groupId>less.lgeo</groupId>
  <licenses>
    <license/>
  </licenses>
  <modelVersion>4.0.0</modelVersion>
  <modules>
    <module>geometry</module>
    <module>parser</module>
    <module>util</module>
    <module>reducer</module>
    <module>messaging</module>
  </modules>
  <name>LessLGEO</name>
  <packaging>pom</packaging>
  <parent>
    <artifactId>spring-boot-starter-parent</artifactId>
    <groupId>org.springframework.boot</groupId>
    <relativePath/>
    <version>3.4.4</version>
  </parent>
  <properties>
    <java.version>23</java.version>
  </properties>
  <scm>
    <connection/>
    <developerConnection/>
    <tag/>
    <url/>
  </scm>
  <url/>
  <version>0.0.1-SNAPSHOT</version>

</project>
