import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import QueryProvider from "@/components/query-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout( {
	children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
	return (
		<html lang="en">
			<body>
				<Analytics/>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
