syntax = "proto3";

package modeling;

import "common.proto";
import "connectivity.proto";

option java_multiple_files = true;
option java_package = "less.lgeo.primitive";
option java_outer_classname = "Modeling";

message Model {
  repeated Comment comment = 1;
  repeated MetaCommand command = 2;
  repeated Line line = 3;
  repeated Triangle triangle = 4;
  repeated Quadrilateral quadrilateral = 5;
  repeated OptionalLine optionalLine = 6;
  repeated SubFileReference piece = 7;
}

message Line {
  LineType type = 1;
  Color color = 2;
  Vertex p1 = 3;
  Vertex p2 = 4;
}

message Triangle {
  LineType type = 1;
  Color color = 2;
  Vertex p1 = 3;
  Vertex p2 = 4;
  Vertex p3 = 5;
}

message Quadrilateral {
  LineType type = 1;
  Color color = 2;
  Vertex p1 = 3;
  Vertex p2 = 4;
  Vertex p3 = 5;
  Vertex p4 = 6;
}
message OptionalLine {
  LineType type = 1;
  Color color = 2;
  Vertex p1 = 3;
  Vertex p2 = 4;
  Vertex p3 = 5;
  Vertex p4 = 6;
}

message SubFileReference {
  LineType type = 1;
  Color color = 2;
  Matrix matrix = 3;
  Model sub_model = 4;
  string file_name = 5;
  optional Connection piece_connection = 6;
}
