<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>geometry</artifactId>

  <build>
    <plugins>
      <!-- Protobuf plugin to generate Java sources from .proto files -->
      <plugin>
        <artifactId>protobuf-maven-plugin</artifactId>
        <configuration>
          <!-- The protoc artifact should have an os classifer at the end but its not working
           this is hard coded but should be some kind of property -->
          <protocArtifact>
            com.google.protobuf:protoc:${protobuf.version}:exe:osx-x86_64
          </protocArtifact>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
        <groupId>org.xolstice.maven.plugins</groupId>
        <version>0.6.1</version>
      </plugin>

      <!-- OS-maven-plugin: no goals, just adds os.detected.classifier -->
      <plugin>
        <artifactId>os-maven-plugin</artifactId>
        <groupId>kr.motd.maven</groupId>
        <version>1.7.1</version>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <!-- https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java -->
    <dependency>
      <artifactId>protobuf-java</artifactId>
      <groupId>com.google.protobuf</groupId>
      <version>4.31.0</version>
    </dependency>
  </dependencies>

  <groupId>less.lgeo</groupId>
  <modelVersion>4.0.0</modelVersion>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>23</maven.compiler.source>
    <maven.compiler.target>23</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <protobuf.version>4.31.0</protobuf.version>
  </properties>

  <version>0.0.1-SNAPSHOT</version>

</project>