<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <artifactId>visualization</artifactId>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <!--Turns out javafx maven plugin conflicts with spring maven plugin, so disable that therefore
              it can rely on other modules with transitive or direct dependencies to parent pom.xml -->
          <artifactId>spring-boot-maven-plugin</artifactId>
          <executions>
            <execution>
              <id>default-cli</id>
              <phase>none</phase>
            </execution>
          </executions>
          <groupId>org.springframework.boot</groupId>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>javafx-maven-plugin</artifactId>
        <configuration>
          <mainClass>less.lgeo.Plot</mainClass>
        </configuration>
        <groupId>org.openjfx</groupId>
        <version>0.0.8</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>javafx-controls</artifactId>
      <groupId>org.openjfx</groupId>
      <version>${javafx.version}</version>
    </dependency>
    <dependency>
      <artifactId>javafx-graphics</artifactId>
      <groupId>org.openjfx</groupId>
      <version>${javafx.version}</version>
    </dependency>
  </dependencies>

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>parent</artifactId>
    <groupId>less.lgeo</groupId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <properties>
    <javafx.version>21</javafx.version>
    <maven.compiler.source>23</maven.compiler.source>
    <maven.compiler.target>23</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <version>0.0.1-SNAPSHOT</version>
</project>
