<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <artifactId>visualization</artifactId>

  <dependencies>
    <!-- Your own module -->
    <dependency>
      <artifactId>parser</artifactId>
      <groupId>less.lgeo</groupId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>

    <!-- LWJGL core -->
    <dependency>
      <artifactId>lwjgl</artifactId>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>
    <dependency>
      <artifactId>lwjgl</artifactId>
      <classifier>natives-macos</classifier>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>

    <!-- LWJGL GLFW -->
    <dependency>
      <artifactId>lwjgl-glfw</artifactId>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>
    <dependency>
      <artifactId>lwjgl-glfw</artifactId>
      <classifier>natives-macos</classifier>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>

    <!-- LWJGL OpenGL -->
    <dependency>
      <artifactId>lwjgl-opengl</artifactId>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>
    <dependency>
      <artifactId>lwjgl-opengl</artifactId>
      <classifier>natives-macos</classifier>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>

    <!-- LWJGL OpenAL -->
    <dependency>
      <artifactId>lwjgl-openal</artifactId>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>
    <dependency>
      <artifactId>lwjgl-openal</artifactId>
      <classifier>natives-macos</classifier>
      <groupId>org.lwjgl</groupId>
      <version>3.3.6</version>
    </dependency>
  </dependencies>

  <modelVersion>4.0.0</modelVersion>
  <packaging>jar</packaging>
  <parent>
    <artifactId>parent</artifactId>
    <groupId>less.lgeo</groupId>
    <relativePath>../pom.xml</relativePath>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <properties>
    <javafx.version>21</javafx.version>
    <maven.compiler.source>23</maven.compiler.source>
    <maven.compiler.target>23</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <version>0.0.1-SNAPSHOT</version>
</project>
