<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <artifactId>bom</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
            <version>${spring.version}</version>
            <optional>true</optional>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <artifactId>spring-boot-starter-web</artifactId>
                <groupId>org.springframework.boot</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>spring-boot-starter-logging</artifactId>
                <groupId>org.springframework.boot</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>spring-boot-starter-amqp</artifactId>
                <groupId>org.springframework.boot</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>spring-boot-starter-data-jpa</artifactId>
                <groupId>org.springframework.boot</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>jakarta.persistence-api</artifactId>
                <groupId>jakarta.persistence</groupId>
                <version>${jakarta-persistence.version}</version>
            </dependency>
            <dependency>
                <artifactId>spring-boot-docker-compose</artifactId>
                <groupId>org.springframework.boot</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>spring-boot-starter-test</artifactId>
                <groupId>org.springframework.boot</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>spring-rabbit-test</artifactId>
                <groupId>org.springframework.amqp</groupId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <artifactId>protobuf-java-util</artifactId>
                <groupId>com.google.protobuf</groupId>
                <version>${protobuf.version}</version>
            </dependency>
            <dependency>
                <artifactId>ejml-core</artifactId>
                <groupId>org.ejml</groupId>
                <version>${ejml.version}</version>
            </dependency>
            <dependency>
                <artifactId>ejml-ddense</artifactId>
                <groupId>org.ejml</groupId>
                <version>${ejml.version}</version>
            </dependency>
            <dependency>
                <artifactId>junit-jupiter-api</artifactId>
                <groupId>org.junit.jupiter</groupId>
                <version>${junit-jupiter.version}</version>
            </dependency>
            <dependency>
                <artifactId>postgresql</artifactId>
                <groupId>org.postgresql</groupId>
                <version>${postgresql.version}</version>
            </dependency>
            <dependency>
                <artifactId>jackson-databind</artifactId>
                <groupId>com.fasterxml.jackson.core</groupId>
                <version>${jackson-bom.version}</version>
            </dependency>
            <dependency>
                <artifactId>liquibase-core</artifactId>
                <groupId>org.liquibase</groupId>
                <version>${liquibase.version}</version>
            </dependency>
            <dependency>
                <artifactId>lombok</artifactId>
                <groupId>org.projectlombok</groupId>
                <version>${lombok.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <parent>
        <artifactId>parent</artifactId>
        <groupId>less.lgeo</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <properties>
        <ejml.version>0.44.0</ejml.version>
        <protobuf.version>4.31.0</protobuf.version>
        <spring.version>3.5.6</spring.version>
    </properties>

    <version>0.0.1-SNAPSHOT</version>
    
</project>